"""fix: restore missing models and update redemption

Revision ID: 0fd81454531f
Revises: 11a345a47b66
Create Date: 2026-06-02 16:36:43.179156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0fd81454531f'
down_revision: Union[str, Sequence[str], None] = 'ca6361356701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    # Types are not returned in existing_tables, we can safely just run DROP TYPE IF EXISTS
    op.execute("DROP TYPE IF EXISTS binstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS shgstatus CASCADE")
    
    if 'bins' in existing_tables:
        op.execute("DROP TABLE IF EXISTS bins CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    if 'reward_items' not in existing_tables:
        op.create_table('reward_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('point_cost', sa.Integer(), nullable=False),
        sa.Column('stock_quantity', sa.Integer(), nullable=True),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    reward_items_indexes = [i['name'] for i in inspector.get_indexes('reward_items')] if 'reward_items' in inspector.get_table_names() else []
    if 'ix_reward_items_id' not in reward_items_indexes:
        op.create_index(op.f('ix_reward_items_id'), 'reward_items', ['id'], unique=False)
        
    if 'bins' not in existing_tables:
        op.create_table('bins',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=100), nullable=False),
        sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('address', sa.String(length=500), nullable=True),
        sa.Column('zone_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('empty', 'inactive', 'low', 'medium', 'high', 'full', 'overflow', 'partial', 'critical', name='binstatus'), nullable=False),
        sa.Column('fill_level', sa.Integer(), nullable=True),
        sa.Column('capacity_kg', sa.Float(), nullable=True),
        sa.Column('last_collected', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    bins_indexes = [i['name'] for i in inspector.get_indexes('bins')] if 'bins' in inspector.get_table_names() else []
    if 'idx_bins_location' not in bins_indexes:
        op.execute('CREATE INDEX IF NOT EXISTS idx_bins_location ON bins USING gist (location)') #, 'bins', ['location'], unique=False, postgresql_using='gist')
    if 'ix_bins_id' not in bins_indexes:
        op.create_index(op.f('ix_bins_id'), 'bins', ['id'], unique=False)

    if 'bin_reports' not in existing_tables:
        op.create_table('bin_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bin_id', sa.Integer(), nullable=False),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('fill_level', sa.Integer(), nullable=True),
        sa.Column('waste_type', sa.String(length=100), nullable=True),
        sa.Column('urgency', sa.String(length=50), nullable=True),
        sa.Column('ai_confidence', sa.Float(), nullable=True),
        sa.Column('ai_observations', sa.Text(), nullable=True),
        sa.Column('reporter_lat', sa.Float(), nullable=True),
        sa.Column('reporter_lng', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
        sa.Column('verified_by', sa.Integer(), nullable=True),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ),
        sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    bin_reports_indexes = [i['name'] for i in inspector.get_indexes('bin_reports')] if 'bin_reports' in inspector.get_table_names() else []
    if 'ix_bin_reports_bin_id' not in bin_reports_indexes:
        op.create_index(op.f('ix_bin_reports_bin_id'), 'bin_reports', ['bin_id'], unique=False)
    if 'ix_bin_reports_id' not in bin_reports_indexes:
        op.create_index(op.f('ix_bin_reports_id'), 'bin_reports', ['id'], unique=False)
    if 'ix_bin_reports_verified_by' not in bin_reports_indexes:
        op.create_index(op.f('ix_bin_reports_verified_by'), 'bin_reports', ['verified_by'], unique=False)

    if 'shg_reports' not in existing_tables:
        op.create_table('shg_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shg_user_id', sa.Integer(), nullable=False),
        sa.Column('bin_id', sa.Integer(), nullable=True),
        sa.Column('zone_id', sa.Integer(), nullable=False),
        sa.Column('plastic_collected_kg', sa.Float(), nullable=False),
        sa.Column('plastic_type', sa.String(length=100), nullable=True),
        sa.Column('fill_level', sa.Integer(), nullable=True),
        sa.Column('collection_point', sa.String(length=255), nullable=True),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['bin_id'], ['bins.id'], ),
        sa.ForeignKeyConstraint(['shg_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    shg_reports_indexes = [i['name'] for i in inspector.get_indexes('shg_reports')] if 'shg_reports' in inspector.get_table_names() else []
    if 'ix_shg_reports_bin_id' not in shg_reports_indexes:
        op.create_index(op.f('ix_shg_reports_bin_id'), 'shg_reports', ['bin_id'], unique=False)
    if 'ix_shg_reports_id' not in shg_reports_indexes:
        op.create_index(op.f('ix_shg_reports_id'), 'shg_reports', ['id'], unique=False)
    if 'ix_shg_reports_shg_user_id' not in shg_reports_indexes:
        op.create_index(op.f('ix_shg_reports_shg_user_id'), 'shg_reports', ['shg_user_id'], unique=False)
    if 'ix_shg_reports_zone_id' not in shg_reports_indexes:
        op.create_index(op.f('ix_shg_reports_zone_id'), 'shg_reports', ['zone_id'], unique=False)

    redemptions_cols = [c['name'] for c in inspector.get_columns('redemptions')] if 'redemptions' in existing_tables else []
    redemptions_indexes = [i['name'] for i in inspector.get_indexes('redemptions')] if 'redemptions' in existing_tables else []
    redemptions_fks = [fk['name'] for fk in inspector.get_foreign_keys('redemptions')] if 'redemptions' in existing_tables else []

    if 'user_id' not in redemptions_cols:
        op.add_column('redemptions', sa.Column('user_id', sa.Integer(), nullable=False))
    if 'item_id' not in redemptions_cols:
        op.add_column('redemptions', sa.Column('item_id', sa.Integer(), nullable=False))
    if 'points_spent' not in redemptions_cols:
        op.add_column('redemptions', sa.Column('points_spent', sa.Integer(), nullable=False))
    if 'status' not in redemptions_cols:
        op.add_column('redemptions', sa.Column('status', sa.String(length=20), nullable=True))
        
    # Checking if id is already integer is tricky without detailed inspection, 
    # but we can check if it's already an integer type or if we should execute it.
    # We will wrap it in a try-except or check the type
    if 'redemptions' in existing_tables:
        id_col = next((c for c in inspector.get_columns('redemptions') if c['name'] == 'id'), None)
        if id_col and not isinstance(id_col['type'], sa.Integer):
            op.alter_column('redemptions', 'id',
                       existing_type=sa.VARCHAR(length=36),
                       type_=sa.Integer(),
                       existing_nullable=False,
                       autoincrement=True)

    if 'ix_redemptions_citizen_house_id' in redemptions_indexes:
        op.drop_index(op.f('ix_redemptions_citizen_house_id'), table_name='redemptions')
    if 'ix_redemptions_merchant_id' in redemptions_indexes:
        op.drop_index(op.f('ix_redemptions_merchant_id'), table_name='redemptions')
        
    if 'ix_redemptions_id' not in redemptions_indexes:
        op.create_index(op.f('ix_redemptions_id'), 'redemptions', ['id'], unique=False)
        
    if 'redemptions_citizen_house_id_fkey' in redemptions_fks:
        op.drop_constraint(op.f('redemptions_citizen_house_id_fkey'), 'redemptions', type_='foreignkey')
    if 'redemptions_merchant_id_fkey' in redemptions_fks:
        op.drop_constraint(op.f('redemptions_merchant_id_fkey'), 'redemptions', type_='foreignkey')
        
    if 'redemptions_user_id_fkey' not in redemptions_fks:
        op.create_foreign_key('redemptions_user_id_fkey', 'redemptions', 'users', ['user_id'], ['id'])
    if 'redemptions_item_id_fkey' not in redemptions_fks:
        op.create_foreign_key('redemptions_item_id_fkey', 'redemptions', 'reward_items', ['item_id'], ['id'])
        
    if 'description' in redemptions_cols:
        op.drop_column('redemptions', 'description')
    if 'points_deducted' in redemptions_cols:
        op.drop_column('redemptions', 'points_deducted')
    if 'merchant_id' in redemptions_cols:
        op.drop_column('redemptions', 'merchant_id')
    if 'citizen_house_id' in redemptions_cols:
        op.drop_column('redemptions', 'citizen_house_id')
    if 'inr_value' in redemptions_cols:
        op.drop_column('redemptions', 'inr_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemptions', sa.Column('inr_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('redemptions', sa.Column('citizen_house_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('redemptions', sa.Column('merchant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('redemptions', sa.Column('points_deducted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('redemptions', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint('redemptions_user_id_fkey', 'redemptions', type_='foreignkey')
    op.drop_constraint('redemptions_item_id_fkey', 'redemptions', type_='foreignkey')
    op.create_foreign_key(op.f('redemptions_merchant_id_fkey'), 'redemptions', 'users', ['merchant_id'], ['id'])
    op.create_foreign_key(op.f('redemptions_citizen_house_id_fkey'), 'redemptions', 'users', ['citizen_house_id'], ['house_id'])
    op.drop_index(op.f('ix_redemptions_id'), table_name='redemptions')
    op.create_index(op.f('ix_redemptions_merchant_id'), 'redemptions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_redemptions_citizen_house_id'), 'redemptions', ['citizen_house_id'], unique=False)
    op.alter_column('redemptions', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('redemptions', 'status')
    op.drop_column('redemptions', 'points_spent')
    op.drop_column('redemptions', 'item_id')
    op.drop_column('redemptions', 'user_id')
    op.drop_index(op.f('ix_shg_reports_zone_id'), table_name='shg_reports')
    op.drop_index(op.f('ix_shg_reports_shg_user_id'), table_name='shg_reports')
    op.drop_index(op.f('ix_shg_reports_id'), table_name='shg_reports')
    op.drop_index(op.f('ix_shg_reports_bin_id'), table_name='shg_reports')
    op.drop_table('shg_reports')
    op.drop_index(op.f('ix_bin_reports_verified_by'), table_name='bin_reports')
    op.drop_index(op.f('ix_bin_reports_id'), table_name='bin_reports')
    op.drop_index(op.f('ix_bin_reports_bin_id'), table_name='bin_reports')
    op.drop_table('bin_reports')
    op.drop_index(op.f('ix_bins_id'), table_name='bins')
    op.drop_index('idx_bins_location', table_name='bins', postgresql_using='gist')
    op.drop_table('bins')
    op.drop_index(op.f('ix_reward_items_id'), table_name='reward_items')
    op.drop_table('reward_items')
    # ### end Alembic commands ###
